startapp/comet/comet/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startapp/comet/mainapp/urls.py
from django.urls import path

from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.intro, name='intro'),
    path('instruction', views.instruction, name='instruction'),
    path('instruction2', views.instruction2, name='instruction2'),
    path('results', views.results, name='results'),
    path('errorpage', views.errorpage, name='errorpage'),
    path('download', views.download_file, name='download'),
    path('track-page', views.track_page, name='track-page'),

    path('faq', views.faq, name='faq'),
    path('info', views.info, name='info'),
    path('privacy', views.privacy, name='privacy'),

    path('tech_doc', views.tech_doc, name='tech_doc'),
    path('tech_attack', views.tech_attack, name='tech_attack'),
    path('tech_install', views.tech_install, name='tech_install'),
    path('tech_ver1', views.tech_ver1, name='tech_ver1'),
    path('tech_ver3', views.tech_ver3, name='tech_ver3'),
    path('tech_ver4', views.tech_ver4, name='tech_ver4'),
    path('tech_mixnet', views.tech_mixnet, name='tech_mixnet'),      
]

startapp/comet/mainapp/models.py
from django.db import models

# Create your models here.
class Website(models.Model):
    url_name      = models.CharField(max_length=100)
    code_name     = models.CharField(max_length=50)
    total_count   = models.IntegerField()
   
    
    def __str__(self):
        return  str(self.url_name)


class PageVisit(models.Model):
    page_name = models.CharField(max_length=255)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    duration = models.IntegerField()

startapp/comet/mainapp/views.py
# Import mimetypes module
import mimetypes
import os
import random

from django.conf import settings
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.db.models import F
from django.http import HttpResponse, FileResponse, JsonResponse


# Reportlab
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import io
import uuid
import random
from .models import Website, PageVisit


from localStoragePy import localStoragePy
localStorage = localStoragePy('local.store.app', 'text')


# Create your views here.
def intro(request):
    
    context ={   
        "urlLink" :"http://app1.res50.itu.dk/instruction", 
    }

    return render(request, 'mainapp/intro.html', context)



def instruction(request):
    urls = Website.objects.all().filter(total_count__lte=130).values()
    if urls:
        urlselected = random.choice(urls)
        urls.filter(url_name=urlselected["url_name"]).update(total_count = F("total_count") + 1)
        var_selected = urlselected["url_name"]
        code_name = urlselected["code_name"] 
    else:
        var_selected = "Admin"
        code_name = "None"
    
    if code_name == "APP2":
        st_code = "INFO"
    elif code_name == "APP3":
        st_code = "UND"
    elif code_name == "APP8":
        st_code = "BAS"
    elif code_name == "APP9":
        st_code = "DEF"
    elif code_name == "APP4":
        st_code = "ALL"
    else:
        return redirect('mainapp:errorpage')
    
    context ={   
        "st_code":st_code,
        "urlselected" : var_selected,
        "code_name": code_name,
    }
    return render(request, 'mainapp/instruction.html', context)



def instruction2(request):
    context ={   
    
    }
    return render(request, 'mainapp/instruction2.html', context)



def results(request):
    context ={   
    }
    return render(request, 'mainapp/results.html', context)




# Election information
def faq(request):
    
    context = { 
           
    }
    return render(request, 'mainapp/faq.html', context)


def info(request):
    
    context = { 
    
    }
    return render(request, 'mainapp/info.html', context)


def privacy(request):
    context = {
    }
    return render(request, 'mainapp/privacy.html', context)




def errorpage(request):
    context ={   
    }
    return render(request, 'mainapp/errorpage.html', context)



def tech_doc(request):
    context ={   
    }
    return render(request, 'mainapp/extrack/documentation.heliosvoting.org/index.html', context)


def tech_attack(request):
    context ={   
    }
    return render(request, 'mainapp/extrack/documentation.heliosvoting.org/attacks-and-defenses.html', context)


def tech_install(request):
    context ={   
    }
    return render(request, 'mainapp/extrack/documentation.heliosvoting.org/install.html', context)


def tech_ver1(request):
    context ={   
    }
    return render(request, 'mainapp/extrack/documentation.heliosvoting.org/verification-specs/helios-v1-and-v2-verification-specs.html', context)


def tech_ver3(request):
    context ={   
    }
    return render(request, 'mainapp/extrack/documentation.heliosvoting.org/verification-specs/helios-v3-verification-specs.html', context)


def tech_ver4(request):
    context ={   
    }
    return render(request, 'mainapp/extrack/documentation.heliosvoting.org/verification-specs/helios-v4.html', context)


def tech_mixnet(request):
    context ={   
    }
    return render(request, 'mainapp/extrack/documentation.heliosvoting.org/verification-specs/mixnet-support.html', context)





def download_file(request):
    #Get candidates to vote for the
    BC = ["Trisha Nunn","Bullock Mason","Chantel Origi"]
    BS = ["Hans Sapei","Ben Cassie","Vannesa Toffic"]
    
    BC_SELECT = random.choice(BC)
    BS_SELECT = random.choice(BS)
    
    
    # Create a file-like buffer to receive PDF data
    output = io.BytesIO()

    # Create the PDF object, using the buffer as its "file"
    p = canvas.Canvas(output, pagesize=letter)

    # Get dynamic content from the request or other sources
    title = request.GET.get('title', 'SECURE E2E INTERNET VOTING')

    # # Start writing the PDF content
    p.setFont("Helvetica-Bold", 18)
    
    # Calculate the center coordinates for the page
    page_width, page_height = letter
    text_width = p.stringWidth(title, "Helvetica-Bold", 18)
    center_x = (page_width - text_width) / 2
    center_y = page_height / 2

    # Center the text on the page
    p.drawCentredString(center_x + 120, 750, title)
    


    p.setFont("Helvetica-Bold", 14)
    p.drawString(30, 710, 'Study Instructions:')
    
    # Add more dynamic content as needed
    
    # Start writing the PDF content
    p.setFont("Helvetica", 12)
    p.drawString(30, 680, 'For the purpose of this study, you are a board member about to vote online in the board election.')
    
    p.setFont("Helvetica", 12)
    p.drawString(30, 660, 'Your task in this study is to cast your vote for your preferred candidate for the Board Chairperson')

    p.setFont("Helvetica", 12)
    p.drawString(30, 640, 'and Board Secretary positions.')
 
    
    #p.setFont("Helvetica-Bold", 12)
    #p.drawString(30, 630, 'Board Chairperson : ' + BC_SELECT)
    #p.setFont("Helvetica-Bold", 12)
    #p.drawString(30, 610, 'Board Secretary : ' + BS_SELECT)
    
    
    
    p.setFont("Helvetica", 12)
    p.drawString(30, 610, 'During the voting, you will be asked to authenticate using the credentials shown to you in the')
    p.setFont("Helvetica", 12)
    p.drawString(30, 590, 'the voting interface. Note, in a real-world elections the credentials will be issued to you separately')
    p.setFont("Helvetica", 12)
    p.drawString(30, 570, 'using secure communication channels and will not be displayed anywhere in the system.')
    

    
    # ...

    # Close the PDF object cleanly and finish the document
    p.showPage()
    p.save()

    # Generate a unique file name
    file_name = str(uuid.uuid4()) + '.pdf'

    # Set the appropriate response headers
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename="{}"'.format(file_name)

    # Write the PDF file to the response
    output.seek(0)
    response.write(output.getvalue())
    
    return response



@csrf_exempt  # Disable CSRF protection for simplicity (you can enable it with proper configuration)
def track_page(request):
    if request.method == 'POST':
        page_name = request.POST.get('page_name')
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')
        duration = request.POST.get('duration')
        
        # Convert duration to seconds
        duration_seconds = int(duration) // 1000
        print(duration)
        print(duration_seconds)

        # Create a new PageVisit object and save it to the database
        PageVisit.objects.create(
            page_name=page_name,
            start_time=start_time,
            end_time=end_time,
            duration=duration_seconds
        )

        return JsonResponse({'message': 'Time recorded successfully.'})

    return JsonResponse({'error': 'Invalid request method.'}, status=400)

startapp/comet/templates/mainapp/errorpage.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Secure E2E Voting</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 
  </head>

  <body style="background-color: darkgreen; color: white;">

   
    <div class="container" >

      <div class="row">
        <div class="col-12">
          <h1 style="text-align: center;">Technical Issues</h1>
          <p class="lead">There is a technical issue, contact an election administrator</p>

        </div>
      </div>
      <hr>
     
      <div class="row">
        <div class="col-4">
          <a href="#" class="btn btn-success btn-lg btn-block" role="button">
            Contact election administrator
          </a> 
        </div>
      </div>

   

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"><\/script>')</script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
  </body>
</html>

startapp/comet/templates/mainapp/info.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Information Availability</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 
  </head>
  <body>
   
    <!-- Menu bar -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: darkgreen">
      <a class="navbar-brand" href="#">SECURE E2E</a>
    </nav>

    <div class="container text-dark mt-2" style="background-color: #ffffff; border: 1px solid #008000;">
        <div class="row" style="background-color: darkgreen; border: 1px solid #008000;">
            <div class="col-lg-12" >
              <h2 class="text-center text-white">Documentation</h2>
            </div>
        </div>
   
        <div class="row">
              <div class="col-lg-12 m-2  text-justify">
               <p>
                  The Secure E2E Voting technology is based on advanced peer-reviewed
                  cryptographic techniques that enable your vote to remain secret while
                  providing an intelligent ballot tracker to let you verify that your
                  ballot was received and counted properly:
                </p>
              </div>  
        </div>
		
        <div class="row">
              <div class="col-lg-12 m-2  text-left">
                <ul>
                  <li> <a target="_new" href="{% url 'mainapp:tech_doc' %}">technical documentation</a></li>
                  <li> <a target="_new" href="http://www.usenix.org/events/sec08/tech/full_papers/adida/adida.pdf">original peer-reviewed (Usenix Security 2008)</a></li>
                  <li> <a target="_new" href="https://github.com/google/pyrios">Pyrios</a> that verifies Helios elections.
                 
                  </ul>
              </div>  
        </div>
		

		
        <div class="row">
          <a id="button-2"  style="margin: auto;"></a> 
        </div>

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/sam/jquery-3.7.0.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/sam/jquery-3.7.0.min.js' %}"><\/script>')</script>    

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{% static 'js/sam/page_tracker.js' %}"></script>
    
    <script>

      let storedCode = localStorage.getItem("st_code");
      if (storedCode == "INFO") {
        urlLink = "https://app2.res50.itu.dk/helios/e/boardelections/vote"
      } else if (storedCode == "ALL"){
        urlLink = "/faq"
      }

      // Get a reference to the button element
      var button = document.getElementById('button-2');
      // IIFE to blink the initial text and stop after 10 seconds 
      (function (){
        button.setAttribute("class", "text-success");
        button.innerHTML = 'Wait for the <b>Next</b> button to Show'
        /*let interval = setInterval(function() {
          button.style.visibility = (button.style.visibility === 'hidden') ? 'visible' : 'hidden';
        }, 1000); // Toggle visibility every 500 milliseconds (0.5 seconds)

        setTimeout(function() {
          clearInterval(interval); // Stop the blinking interval
          button.style.visibility = 'visible'; // Ensure text is visible after blinking stops
        }, 10000); // Stop blinking after 5 seconds (5000 milliseconds)
       */
      })();


      // Enable the button after 10 seconds (10000 milliseconds)
      setTimeout(function() {
        button.setAttribute("href", urlLink);
        button.setAttribute("class", "btn btn-success btn-lg mb-3");
        button.setAttribute("role", "button");
        button.innerText = "Next";
        button.onclick = null;
      }, 10000);
    </script>    
    

  </body>
</html>

startapp/comet/templates/mainapp/instruction.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Study Instructions</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 
  </head>
  <body>
   
    <!-- Menu bar -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: darkgreen">
      <a class="navbar-brand" href="#">SECURE E2E</a>
    </nav>

   <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">COMET Voting</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Privacy</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Integrity Measures</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Security Assurance</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">FAQs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
          </li>
        </ul>
      </div>
    </nav>-->
    <!-- Menu bar ends here -->
    <!--  -->
    <div class="container text-white mt-2" style="background-color: #ffffff; border: 1px solid #008000;">
      <div class="row" style="background-color: darkgreen; border: 1px solid #008000;">
          <div class="col-lg-12" >
            <h2 class="text-center text-white">Study Instructions</h2>
          </div>
      </div>
      <div class="row text-dark" style=" border: 1px solid #008000;">
          <div class="col-lg-12 mt-3  text-left">
            
            <p class="text-justify">
              For the purpose of this study, you are a board member about to vote online in the board election. 
              Your task in this study is to cast your vote for your preferred candidate for the Board Chairperson and Board Secretary positions. 
            </p> 
              <!-- Board Chairperson: <b>{{ BC_SELECT }}</b> <br />
            Board Secretary  :  <b>{{ BS_SELECT }}</b><br /> <br /> -->
            <p class="text-justify">
              During the voting, you will be asked to authenticate using the credentials shown to you in the voting interface. 
              Note, in a real-world elections the credentials will be issued to you separately using secure communication channels and will not be displayed anywhere in the system. 
            </p>

            <p class="text-justify">
              You can also download these instructions for a later reference by clicking on the 
              <b class="text-success">Download</b> below. When you are ready to start the study, please click <b class="text-success">Next</b> 
            </p>
          </div>
        </div>
         <div class="row" style="background-color: #ffffff; border: 1px solid #008000;">
          <div class="col-lg-3 m-2">
            <a id="button-1" target="_blank" href="{% url 'mainapp:download' %}" class="btn btn-success btn-lg btn-block" role="button">
              Download
            </a> 
          </div>
          <div class="col-lg-3 m-2" style="margin: auto;">
            <a id="button-2"  style="margin: auto;"></a> 
          </div>
        </div>  
      </div>
     


    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/sam/jquery-3.7.0.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/sam/jquery-3.7.0.min.js' %}"><\/script>')</script>    

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{% static 'js/sam/page_tracker.js' %}"></script>

    <script>

      //set local storage
      let storedCode = localStorage.getItem("st_code");
      
      if (storedCode){
        //alert(storedCode + " already exist");
        if (storedCode == "DEF") {
          urlLink ="https://app9.res50.itu.dk/helios/e/boardelections/vote"
        } else if (storedCode == "BAS") {
          urlLink = "/instruction2"
        } else if (storedCode == "UND") {
          urlLink = "/instruction2"
        } else if (storedCode == "INFO") {
          urlLink = "/instruction2"
        } else if (storedCode == "ALL") {
          urlLink = "/instruction2"
        }
      }
      else {
        //alert("Set a new storage");
        localStorage.setItem("st_code", "{{st_code}}");
        if ("{{st_code}}" == "DEF") {
          urlLink ="https://app9.res50.itu.dk/helios/e/boardelections/vote"
        } else if ("{{st_code}}" == "BAS") {
          urlLink = "/instruction2"
        } else if ("{{st_code}}" == "UND") {
          urlLink = "/instruction2"
        } else if ("{{st_code}}" == "INFO") {
          urlLink = "/instruction2"       
        } else if ("{{st_code}}" == "ALL") {
          urlLink = "/instruction2"
        } else {
          alert("Error setting")
        }
      }
      
      // Get a reference to the button element
      var button = document.getElementById('button-2');

      // IIFE to blink the initial text and stop after 10 seconds 
      (function (){
        button.setAttribute("class", "text-success");
        button.innerHTML = 'Wait for the <b>Next</b> button to Show'

       /* let interval = setInterval(function() {
          button.style.visibility = (button.style.visibility === 'hidden') ? 'visible' : 'hidden';
        }, 1000); // Toggle visibility every 500 milliseconds (0.5 seconds)

        setTimeout(function() {
          clearInterval(interval); // Stop the blinking interval
          button.style.visibility = 'visible'; // Ensure text is visible after blinking stops
        }, 10000); // Stop blinking after 5 seconds (5000 milliseconds)
       */
      })();


      // Enable the button after 5 seconds (5000 milliseconds)
      setTimeout(function() {
        button.setAttribute("href", urlLink);
        button.setAttribute("class", "btn btn-success btn-lg mb-3 btn-block");
        button.setAttribute("role", "button");
        button.innerText = "Next";
        button.onclick = null;
      }, 10000);

      //href="{{urlLink}}" role="button"  class="btn btn-info btn-lg mb-3"
    </script>

  </body>
</html>

startapp/comet/templates/mainapp/results.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Transparency and Trust Survey</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

 
  </head>
  <body style="background-color: rgb(45, 49, 49);">
   
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: darkgreen">
      <a class="navbar-brand" href="#">SECURE E2E</a>
    </nav>
    <div class="container text-white mt-2" style="background-color: darkgreen">
      
      <div class="row">
        <div class="col-12">
          <p>
            Dear participant, <br> <br>      
          </p>
          <p>
            You have now completed the voting part of the study. You will now be forwarded to the page where you would be able to view 
            the election results - note, in a real-world election this page will only be available after the election has ended. 
            To move to the next stage, click “Next” </p>
          <p>
          
          
          <div class="row">
            <div class="col-3">
              <a  class="btn btn-success btn-lg btn-block" role="button" id="toResults">
                Next
              </a> 
            </div>
          </div>
        </div>

      </div>
      <hr>

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"><\/script>')</script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script>

        button = document.getElementById("toResults")
        let storedCode = localStorage.getItem("st_code");

        if (storedCode == "DEF") {
          app_version = "DEF"
        } else if (storedCode == "BAS") {
          app_version = "BAS"
        } else if (storedCode == "UND") {
          app_version = "UND"
        } else if (storedCode == "INFO") {
          app_version = "INFO"
        } else if (storedCode == "ALL") {
          app_version = "ALL"
        } else {
          alert ("An error has occured")
        }

        urlLink =`https://res50.itu.dk/helios/elections/35ae7f5a-a166-11ed-bdff-e130b8ee647d/view?param=${app_version}`

        button.setAttribute("href", urlLink);
        button.innerText = "Next";
        button.onclick = null;
    </script>

    
  </body>
</html>